rvm:
- 2.1.1
env:
  global:
  - secure: PmDB6UiQXPpw8XWEmAbWHTXnfc8nGZKoWP1n5HWsSX+b95iP8fOeIiU2y0oKpBszpVYLOGn7LSLE/OGE4T/ZJ3PMO422ikPlfUOApUFFhRbDOInqpKJeO9h4Qmt/lWVzHNQ1ePWFRWur69kC1chB46dceMC3N/fv7wGFfmg6jFc=
bundler_args: --without development
language: node_js
node_js:
- '0.10'
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- npm install -g grunt-cli bower
after_success:
- grunt build
- chmod +x deploy.sh
- ./deploy.sh
