rvm:
- 2.1.1
env:
  global:
  - secure: AcQ3VW8VsgzJQQAJl000haAta/rDgX1MGdBcI3VwhOfeuM2yyixFsrnKENYoedNAT5K9M0AtE7KnTSG7/Vjk1EdFrualAuUIjr7IF42kSE6Zfthb8syZW9ELTAtkNaA2cJUAnxqAVo38LwsRkjUrz+by5ZVktMy+3z7+F3P9nRo=
bundler_args: --without development
language: node_js
node_js:
- '0.10'
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- npm install -g grunt-cli bower
after_success:
- grunt build
- chmod +x deploy.sh
- ./deploy.sh
